services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"

#  app:
#    build: .
#    container_name: pet-clinic
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#      - SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
#      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
#      - SERVER_PORT=${SERVER_PORT}
#    ports:
#      - "${SERVER_PORT}:8080"

volumes:
  postgres_data:
